language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge --force
  - conda update --yes conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip nose flake8 numpy matplotlib pandas basemap geopandas
    # - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip nose flake8 numpy matplotlib pandas basemap geopandas
  # - source activate test-environment
  - pip install coveralls 
  - python setup.py install
  # - wget https://downloads.sourceforge.net/project/matplotlib/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz
  # - tar -xzvf basemap-1.0.7.tar.gz
  # - export GEOS_DIR=$HOME/.libgeos/3.5.0/
  # - pushd basemap-1.0.7/geos-3.3.3 && ./configure --prefix=$GEOS_DIR && make && sudo make install && popd
  # - pushd basemap-1.0.7 && python setup.py install && popd
  # - pip install nose coveralls numpy matplotlib flake8 pandas
  # - python setup.py install

script:
  - python run_tests.py

  - flake8 --exit-zero pysplit

after_success:
  coveralls
